apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: inventory-config
          volumeMounts:
            - mountPath: /app/data
              name: inventory-data
      volumes:
        - name: inventory-data
          persistentVolumeClaim:
            claimName: inventory-pvc
